# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_requestedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('popularity', models.PositiveSmallIntegerField(default=0)),
                ('percent_rate', models.FloatField(default=0)),
                ('flat_rate', models.FloatField(default=0)),
                ('volume_rate', models.FloatField(default=0)),
                ('esc', models.FloatField(default=0)),
                ('vat', models.FloatField(default=13)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('sales_tax', models.FloatField(default=0)),
                ('domestic_shipping', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('length', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('link', models.URLField()),
                ('public', models.BooleanField(default=False)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.ItemCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='membership',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
