# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_shop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='harmony_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
