# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0007_itemcategory_harmony_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=website.models.uploadProductPhoto)),
                ('price', models.FloatField(default=0)),
                ('sales_tax', models.FloatField(default=0)),
                ('domestic_shipping', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('length', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('link', models.URLField()),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.ItemCategory')),
                ('quoted_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoter', to=settings.AUTH_USER_MODEL)),
                ('requested_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.RequestedProduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='public',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=website.models.uploadProductPhoto),
        ),
    ]
