# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 08:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20161121_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='requestedproduct',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='deleted',
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 21, 8, 38, 14, 504050, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 21, 8, 38, 26, 49697, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.PositiveIntegerField(),
        ),
    ]
