# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20161121_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sales_tax',
            new_name='approx_taxes',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='sales_tax',
            new_name='approx_taxes',
        ),
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'limited'), (1, 'silver'), (2, 'gold'), (3, 'platinium'), (4, 'vip')]),
        ),
    ]
