# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20161212_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcategory',
            old_name='esc',
            new_name='ecs',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='requested_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='website.RequestedProduct'),
        ),
    ]
