# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20161214_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.PositiveIntegerField(),
        ),
    ]
