from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^sharifaAdmin/dashboard/$', DashboardView.as_view(), name='dashboard'),

    url(r'^sharifaAdmin/login/$', AdminLogInView.as_view(), name='adminLogIn'),
    url(r'^sharifaAdmin/logout/$', AdminLogOutView.as_view(), name='adminLogOut'),

    url(r'^sharifaAdmin/category/list/$',
        ItemCategoryListView.as_view(), name='itemCategoryList'),
    url(r'^sharifaAdmin/category/create/$',
        ItemCategoryCreateView.as_view(), name='itemCategoryCreate'),
    url(r'^sharifaAdmin/category/(?P<slug>[\w-]+)/$',
        ItemCategoryDetailView.as_view(), name='itemCategoryDetail'),
    url(r'^sharifaAdmin/category/(?P<slug>[\w-]+)/delete$',
        ItemCategoryDeleteView.as_view(), name='itemCategoryDelete'),
    url(r'^sharifaAdmin/category/(?P<slug>[\w-]+)/update/$',
        ItemCategoryUpdateView.as_view(), name='itemCategoryUpdate'),

    url(r'^sharifaAdmin/page/list/$', PageListView.as_view(), name='pageList'),
    url(r'^sharifaAdmin/page/create/$',
        PageCreateView.as_view(), name='pageCreate'),
    url(r'^sharifaAdmin/page/(?P<slug>[\w-]+)/$',
        PageDetailView.as_view(), name='pageDetail'),
    url(r'^sharifaAdmin/page/(?P<slug>[\w-]+)/update/$',
        PageUpdateView.as_view(), name='pageUpdate'),
    url(r'^sharifaAdmin/page/(?P<slug>[\w-]+)/delete/$',
        PageDeleteView.as_view(), name='pageDelete'),

    url(r'^sharifaAdmin/product/list/$',
        ProductListView.as_view(), name='productList'),
    url(r'^sharifaAdmin/product/create/$',
        ProductCreateView.as_view(), name='productCreate'),
    url(r'^sharifaAdmin/product/(?P<slug>[\w-]+)/$',
        ProductDetailView.as_view(), name='productDetail'),
    url(r'^sharifaAdmin/product/(?P<slug>[\w-]+)/update/$',
        ProductUpdateView.as_view(), name='productUpdate'),
    url(r'^sharifaAdmin/product/(?P<slug>[\w-]+)/delete/$',
        ProductDeleteView.as_view(), name='productDelete'),
    url(r'^sharifaAdmin/product/create/(?P<pk>\d+)/$',
        ProductCreateFromQuoatationView.as_view(), name='productCreateFromQuotation'),

    url(r'^sharifaAdmin/profile/list/$',
        ProfileListView.as_view(), name='profileList'),

    url(r'^sharifaAdmin/quotation/list/$',
        QuotationListView.as_view(), name='quotationList'),
    url(r'^sharifaAdmin/quotation/create/(?P<id>\d+)/$',
        QuotationCreateView.as_view(), name='quotationCreate'),
    url(r'^sharifaAdmin/quotation/(?P<pk>\d+)/$',
        QuotationDetailView.as_view(), name='quotationDetail'),
    url(r'^sharifaAdmin/quotation/(?P<pk>\d+)/update/$',
        QuotationUpdateView.as_view(), name='quotationUpdate'),
    url(r'^sharifaAdmin/quotation/(?P<pk>\d+)/delete/$',
        QuotationDeleteView.as_view(), name='quotationDelete'),

    url(r'^sharifaAdmin/requestproduct/list/$',
        RequestedProductListView.as_view(), name='requestProductList'),
    url(r'^sharifaAdmin/requestproduct/(?P<pk>\d+)/$',
        RequestedProductDetailView.as_view(), name='requestProductDetail'),
    url(r'^sharifaAdmin/requestproduct/(?P<pk>\d+)/delete/$',
        RequestedProductDeleteView.as_view(), name='requestProductDelete'),

    url(r'^sharifaAdmin/shop/list/$', ShopListView.as_view(), name='shopList'),
    url(r'^sharifaAdmin/shop/create/$',
        ShopCreateView.as_view(), name='shopCreate'),
    url(r'^sharifaAdmin/shop/(?P<pk>\d+)/$',
        ShopDetailView.as_view(), name='shopDetail'),
    url(r'^sharifaAdmin/shop/(?P<pk>\d+)/update/$',
        ShopUpdateView.as_view(), name='shopUpdate'),
    url(r'^sharifaAdmin/shop/(?P<pk>\d+)/delete/$',
        ShopDeleteView.as_view(), name='shopDelete'),

    url(r'^sharifaAdmin/siteconfig/list/$',
        SiteConfigListView.as_view(), name='siteConfigList'),
    url(r'^sharifaAdmin/siteconfig/create/$',
        SiteConfigCreateView.as_view(), name='siteConfigCreate'),
    url(r'^sharifaAdmin/siteconfig/(?P<pk>\d+)/$',
        SiteConfigDetailView.as_view(), name='siteConfigDetail'),
    url(r'^sharifaAdmin/siteconfig/(?P<pk>\d+)/update/$',
        SiteConfigUpdateView.as_view(), name='siteConfigUpdate'),
    url(r'^sharifaAdmin/siteconfig/(?P<pk>\d+)/delete/$',
        SiteConfigDeleteView.as_view(), name='siteConfigDelete'),

    url(r'^sharifaAdmin/staff/list/$', StaffListView.as_view(), name='staffList'),
    url(r'^sharifaAdmin/staff/create/$',
        StaffCreateView.as_view(), name='staffCreate'),
    url(r'^sharifaAdmin/staff/(?P<pk>\d+)/email-change/$',
        StaffEmailChangeView.as_view(), name='staffEmailChange'),
    url(r'^sharifaAdmin/staff/(?P<pk>\d+)/toggle-group/$',
        StaffToggleGroupView.as_view(), name='staffToggleGroup'),

    url(r'^membership/$', MembershipListView.as_view(), name='membershipList'),
    url(r'^membership/(?P<slug>[\w-]+)/$',
        BuyMembership.as_view(), name='buyMembership'),
    url(r'^membership/activate_deactivate/(?P<pkP>\d+)/$',
        MembershipActivateDeactivateView.as_view(), name='activateDeavtivate'),
    url(r'^membership/approve_disapprove/(?P<pk>\d+)/$',
        MembershipApproveDisapproveView.as_view(), name='activateDeavtivate'),

    url(r'^profile/(?P<pk>\d+)/$', ProfileDetailView.as_view(), name='profileDetail'),
    url(r'^profile/(?P<pk>\d+)/update/$',
        ProfileUpdateView.as_view(), name='profileUpdate'),

    url(r'^requestproduct/$', UserRequestedProductCreateView.as_view(),
        name='userRequestProductCreate'),
    url(r'^quotation/(?P<pk>\d+)/$',
        UserQuotationDetailView.as_view(), name='userQuotationDetail'),
    url(r'^shops/$', UserShopListView.as_view(), name='userShopList'),
    url(r'^categories/$', UserItemCategoryListView.as_view(),
        name='userItemCategoryList'),
    url(r'^categories/(?P<slug>[\w-]+)/$',
        UserItemCategoryDetailView.as_view(), name='userItemCategoryDetail'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),


]
